### ISSUE TITLE
blob simulator

### ISSUE THREAD

**Issue by Golden-Piglin** [zSnout/v5.zsnout.com#5]
**Describe the bug**
the blob simulator never works

**To Reproduce**
1. Go to blob simulator
2. Click on blob simulator
3. Scroll down to blob simulator

**Expected behavior**
blob simulator doesn't work

**Screenshots**

**Desktop (please complete the following information):**
 - iOS
 - chrome
 - 2.3.4

**Additional context**
FIX NOW

**Comment by zsakowitz** [comment]
Hey person9876! We've just fixed this issue with [commit 3e2e0bb](https://github.com/zSnout/zsnout.com/commit/3e2e0bb8dfa24df59bc0c90e2fb32741407e0c60).
