### ISSUE TITLE
Clean homepage

### ISSUE THREAD

**Issue by AviationSFO** [zSnout/v5.zsnout.com#6]
**Is your feature request related to a problem? Please describe.**
no, the ui sucks, make things organized rather than a gagiliion options of the homepage
**Describe the solution you'd like**
make things organized rather than a gagiliion options of the homepage
**Describe alternatives you've considered**
there is no other dude, unless you dont do anything

**Additional context**
N/A

**Comment by zsakowitz** [comment]
Due to a new theme system, the theme icons have been removed from the homepage. This should help to solve your problem and we're working on the rest.
